### PR TITLE
List disconnected peers

### LINKED ISSUE #147: list peers should show all peers, even one we aren't connected to
so we can clear out peers that are disconnected for instance

### PR DESCRIPTION
**Pull request by benthecarman**
Closes #147

The return type for this is a `Vec<String>`, maybe we should create a `MutinyPeer` type that has information like `connection_string` and `is_connected` etc

### CODE REVIEW

**Review by TonyGiorgio — CHANGES_REQUESTED** [review]
Yeah actually I think we might need to pass back the object with whether or not it is connected. The frontend has an X button on it so what would happen (or the intention to what should happen) when they click an X on a disconnected peer? 

For one, I wouldn't expect disconnected peers showing up exactly the same as connected ones. That's going to be hard to troubleshoot when issues arise due to disconnected peers. 

For two, if a peer is disconnected and I see it is disconnected, when I click X, I would probably intend for it to be deleted from the DB.

**Comment by benthecarman** [comment]
Updates: 
image

image

**Review by TonyGiorgio — APPROVED** [review]
Rust code looks good, thanks for doing that. @futurepaul might have some additional thoughts when we were testing this.

**Review by futurepaul — APPROVED** [review]
awesome, made a small commit hope you don't mind

**Comment by benthecarman** [comment]
> awesome, made a small commit hope you don't mind

Fixed a small typo

**Pull request merged**
