### PR TITLE
PWA

### PR DESCRIPTION
**Pull request by futurepaul**
added pwa functionality, instructions in readme 

also imported a router and moved our tests to a /tests route so I can start on the "real" ui

this pulls in a ton of workbox dependencies, will probably want to vet these and make sure they aren't actually pulling in google analytics

### CODE REVIEW

**Comment by futurepaul** [comment]
Screen Shot 2022-11-04 at 2 06 20 PM

**Review by benthecarman — APPROVED** [review]
idk js but lgtm

**Review by TonyGiorgio — CHANGES_REQUESTED** [review]
Needs to wait

**Review by TonyGiorgio — APPROVED** [review]
You may proceed

**Pull request merged**
